### PR TITLE
Add XSD schemas

### PR DESCRIPTION
**Pull request by ben221199**
This pull request will add the XSD schemas for Autoconfig Mail.

### CODE REVIEW

**Review by benbucksch — CHANGES_REQUESTED** [review]
Thanks so much for the XSD!

However, I see that it's a schema for the version 1.0, which was in use only for a few months 15 years ago and has since not been used anymore. It doesn't match the spec anymore.

Would you mind updating the XSD with the sample in the current spec?

**Comment by benbucksch** [comment]
@ben221199 I'm going to close this specific PR, because it has only the XSD for 1.0, which was used only few a few months 15 years ago and nobody uses anymore.

If you have an XSD for 1.2, which is what the specification specifies, that would be very helpful. I'd be happy about that. Please do feel free to open another PR for that.

**Comment by ben221199** [comment]
Hi @benbucksch, sorry for my inactivity last months. I had to focus on some other projects. I will finish 1.1 and add 1.2 as soon as I have time.

**Comment by benbucksch** [comment]
@ben221199 No problem. Don't worry much about 1.1, because it's not relevant for the spec here.

**Pull request closed without merging**
